config/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.contrib import admin
from django.views.static import serve

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('zinnia_twts.urls', namespace='zinnia_twts')),
    url(r'', include('zinnia.urls')),
    url(r'^comments/', include('django_comments.urls')),

]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        }),
    ]

zinnia_twts/urls.py
from django.conf.urls import url, include
from . import views

urlpatterns = [
    url(r'^weblog/$', views.WidthEntryIndex.as_view(), name='width_entry_index'),
    url(r'^contact/$', views.ContactView.as_view(), name='contact'),
    url(r'^about/$', views.AboutView.as_view(), name='about'),
]

zinnia_twts/views.py
from django.views.generic import TemplateView

from zinnia.views.archives import EntryIndex


class WidthEntryIndex(EntryIndex):
    template_name = 'zinnia/width_entry_list.html'


class AboutView(TemplateView):
    template_name = 'zinnia/about.html'


class ContactView(TemplateView):
    template_name = 'zinnia/contact.html'

templates/comments/zinnia/entry/form.html
{% load comments i18n %}

<form action="{% comment_form_target %}" method="post" id="comment-form">
    <div>{% csrf_token %}</div>
    {% if form.non_field_errors %}
        <div class="error">
            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <fieldset>
        <legend class="">{% trans "Post your comment" %}</legend>
        <input type="hidden" name="next" value="{% url 'zinnia:comment_success' %}"/>
        {% for field in form %}
            {% if field.is_hidden %}{{ field }}{% else %}
                {% ifequal field.name "comment" %}
                    <div class="col-md-12 right-padding-30">
                {% else %}
                    <div class="col-md-4 right-padding-30">
                {% endifequal %}
            {% if user.email and field.name in "namemailurl" %}{% else %}
                <div{% if field.errors %} class="error"{% endif %}{% ifequal field.name "honeypot" %}
                                          style="display:none;"{% endifequal %}>
                    {{ field.label_tag }}
                    {% if field.errors %}{{ field.errors }}{% endif %}
                    {{ field }}
                </div>
            {% endif %}
            </div>
            {% endif %}
        {% endfor %}
        {% if user.is_authenticated %}
            <p class="auth">
                {% trans "Comment as" %} <strong>{% firstof user.get_full_name user.get_username %}</strong>. <a
                    href="{% url 'admin:logout' %}">{% trans "Log out" %}</a>.
            </p>
        {% endif %}
        <p class="submit">
            <input type="submit" name="submit" class="submit-post pull-right right-margin-30"
                   value="{% trans "Post" %}"/>
            <input type="submit" name="preview" class="submit-preview pull-right right-margin-30"
                   value="{% trans "Preview" %}"/>
        </p>
    </fieldset>
</form>

templates/comments/zinnia/entry/posted.html
{% extends "zinnia/base.html" %}
{% load i18n %}

{% block title %}{% trans "Thanks for your comment" %}{% endblock title %}

{% block body-class %}comment-posted{% endblock body-class %}

{% block content %}
    <h2>{% trans "Thanks for your comment" %}</h2>

    <p>{% trans "Your comment needs to be approved before getting displayed." %}</p>

    <ul>
        {% if comment %}
            <li>
                {% with entry=comment.content_object %}
                    <a href="{{ entry.get_absolute_url }}"
                       title="{{ entry.title }}">
                        {% blocktrans with title=entry.title %}Back to {{ title }}{% endblocktrans %}
                    </a>
                {% endwith %}
            </li>
        {% endif %}
        <li>
            <a href="{% url 'zinnia:entry_archive_index' %}"
               title="{% trans "Return to entry list" %}">
                {% trans "Return to entry list" %}
            </a>
        </li>
    </ul>
{% endblock content %}

templates/zinnia/about.html
{% extends 'zinnia/skeleton.html' %}
{% load staticfiles %}
{% block content_body %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    <h1 class="page-title">About Me</h1>
                    <article class="post">
                        <div class="entry-content clearfix">
                            <figure class="img-responsive-center">
                                <img class="img-responsive" src="{% static 'zinnia_twts/theme/img/me.jpg' %}" alt="Developer Image">
                            </figure>
                            <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb
                                and flow of things. There are many variations of passages of Lorem Ipsum available, but
                                the majority have suffered alteration in some form, by injected humour, or randomised
                                words which don’t look even slightly.</p>
                            <p>Responsive web design offers us a way forward, finally allowing us to design for the ebb
                                and flow of things. There are many variations of passages of Lorem Ipsum available, but
                                the majority have suffered alteration in some form, by injected humour, or randomised
                                words which don’t look even slightly.</p>
                            <div class="height-40px"></div>
                            <h2 class="title text-center">Social</h2>
                            <ul class="social">
                                <li class="facebook"><a href="#"><span class="ion-social-facebook"></span></a></li>
                                <li class="twitter"><a href="#"><span class="ion-social-twitter"></span></a></li>
                                <li class="google-plus"><a href="#"><span class="ion-social-googleplus"></span></a></li>
                                <li class="tumblr"><a href="#"><span class="ion-social-tumblr"></span></a></li>
                            </ul>
                        </div>
                    </article>
                </main>
            </div>
        </div>
    </div>
{% endblock %}

templates/zinnia/base.html
{% extends "zinnia/skeleton.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-keywords %}{% get_tags as entry_tags %}{{ entry_tags|join:", " }}{% endblock meta-keywords %}

{% block meta %}
    <meta name="generator" content="Zinnia {{ ZINNIA_VERSION }}"/>
{% endblock meta %}

{% block link %}
    <link rel="index" href="{% url 'zinnia:entry_archive_index' %}"/>
    <link rel="author" type="text/plain" href="{% url 'zinnia:humans' %}"/>
    <link rel="EditURI" type="application/rsd+xml" href="{% url 'zinnia:rsd' %}"/>
    <link rel="wlwmanifest" type="application/wlwmanifest+xml" href="{% url 'zinnia:wlwmanifest' %}"/>
    <link rel="search" type="application/opensearchdescription+xml" title="Zinnia's Weblog"
          href="{% url 'zinnia:opensearch' %}"/>
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last entries" %}"
          href="{% url 'zinnia:entry_feed' %}"/>
    <link rel="alternate" type="application/rss+xml" title="{% trans "RSS feed of last discussions" %}"
          href="{% url 'zinnia:discussion_feed' %}"/>
    {% get_archives_entries "zinnia/tags/entries_archives_link.html" %}
{% endblock link %}

{% block breadcrumbs %}
    {% trans "Blog" as root_name %}
    {% zinnia_breadcrumbs root_name %}
{% endblock breadcrumbs %}

{% block sidebar %}
    <div class="widget widget-recent-posts">
        <h3 class="widget-title">{% trans "Recent entries" %}</h3>
        {% get_recent_entries %}
        {#            <li>#}
        {#                <a href="#">Adaptive Vs. Responsive Layouts And Optimal Text Readability</a>#}
        {#            </li>#}
        {#            <li>#}
        {#                <a href="#">Web Design is 95% Typography</a>#}
        {#            </li>#}
        {#            <li>#}
        {#                <a href="#">Paper by FiftyThree</a>#}
        {#            </li>#}
    </div>
    <div class="widget widget-archives">
        <h3 class="widget-title">{% trans "Archives" %}</h3>
        {% get_archives_entries_tree %}
    </div>

    <div class="widget widget-category">
        <h3 class="widget-title">{% trans "Categories" %}</h3>
        {% get_categories %}
    </div>

    <div class="widget widget-cloud">
        <h3 class="widget-title"><a href="{% url 'zinnia:tag_list' %}">{% trans "Tags" %}</a></h3>
        {% get_tag_cloud %}
    </div>

    {#<aside id="widget-welcome" class="widget">#}
    {#  <h3>{% trans "Welcome!" %}</h3>#}
    {#  <p>#}
    {#    {% trans "This simple theme is the default appearance of Zinnia." %}#}
    {#  </p>#}
    {#  <p>#}
    {#    {% trans "Don't hesitate to override the template <strong>zinnia/base.html</strong> to start <a href='http://docs.django-blog-zinnia.com/en/latest/how-to/customize_look_and_feel.html'>customizing your Weblog</a>." %}#}
    {#  </p>#}
    {#</aside>#}
    {#<aside id="widget-categories" class="widget">#}
    {#  <h3>#}
    {#    <a href="{% url 'zinnia:category_list' %}">{% trans "Categories" %}</a>#}
    {#  </h3>#}
    {#  {% get_categories %}#}
    {#</aside>#}
    {#<aside id="widget-authors" class="widget">#}
    {#  <h3>#}
    {#    <a href="{% url 'zinnia:author_list' %}">{% trans "Authors" %}</a>#}
    {#  </h3>#}
    {#  {% get_authors %}#}
    {#</aside>#}
    {#<aside id="widget-calendar" class="widget">#}
    {#  <h3>{% trans "Calendar" %}</h3>#}
    {#  {% get_calendar_entries %}#}
    {#</aside>#}
    {#<aside id="widget-tags" class="widget">#}
    {#  <h3>#}
    {#    <a href="{% url 'zinnia:tag_list' %}">{% trans "Tags" %}</a>#}
    {#  </h3>#}
    {#  {% get_tag_cloud %}#}
    {#</aside>#}
    {#<aside id="widget-recents" class="widget">#}
    {#  <h3>{% trans "Recent entries" %}</h3>#}
    {#  {% get_recent_entries %}#}
    {#</aside>#}
    {#<aside id="widget-comments" class="widget">#}
    {#  <h3>{% trans "Recent comments" %}</h3>#}
    {#  {% get_recent_comments %}#}
    {#</aside>#}
    {#<aside id="widget-linkbacks" class="widget">#}
    {#  <h3>{% trans "Recent linkbacks" %}</h3>#}
    {#  {% get_recent_linkbacks %}#}
    {#</aside>#}
    {#<aside id="widget-randoms" class="widget">#}
    {#  <h3>{% trans "Random entries" %}</h3>#}
    {#  {% get_random_entries %}#}
    {#</aside>#}
    {#<aside id="widget-populars" class="widget">#}
    {#  <h3>{% trans "Popular entries" %}</h3>#}
    {#  {% get_popular_entries %}#}
    {#</aside>#}
    {#<aside id="widget-archives" class="widget">#}
    {#  <h3>{% trans "Archives" %}</h3>#}
    {#  {% get_archives_entries_tree %}#}
    {#</aside>#}
    {#{% if user.is_authenticated %}#}
    {#<aside id="widget-tools" class="widget">#}
    {#  <h3>{% trans "Tools" %}</h3>#}
    {#  <ul>#}
    {#    {% if perms.zinnia %}#}
    {#    <li>#}
    {#      <a href="{% url 'admin:app_list' 'zinnia' %}" title="{% trans "Dashboard" %}">#}
    {#        {% trans "Dashboard" %}#}
    {#      </a>#}
    {#    </li>#}
    {#    {% endif %}#}
    {#    {% if perms.zinnia.add_entry %}#}
    {#    <li>#}
    {#      <a href="{% url 'admin:zinnia_entry_add' %}" title="{% trans "Post an entry" %}">#}
    {#        {% trans "Post an entry" %}#}
    {#      </a>#}
    {#    </li>#}
    {#    {% endif %}#}
    {#    {% block admin-tools %}#}
    {#    {% endblock admin-tools %}#}
    {#    <li>#}
    {#      <a href="{% url 'admin:logout' %}" title="{% trans "Log out" %}">#}
    {#        {% trans "Log out" %}#}
    {#      </a>#}
    {#    </li>#}
    {#  </ul>#}
    {#</aside>#}
    {#{% endif %}#}
{% endblock sidebar %}

templates/zinnia/contact.html
{% extends 'zinnia/skeleton.html' %}
{% load staticfiles %}
{% block content_body %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                <main class="col-md-12">
                    <h1 class="page-title">Contact</h1>
                    <article class="post">
                        <div class="entry-content clearfix">
                            <form action="#" method="post" class="contact-form">
                                <div class="row">
                                    <div class="col-md-6 col-md-offset-3">
                                        <input type="text" name="name" placeholder="Name" required>
                                        <input type="email" name="email" placeholder="Email" required>
                                        <input type="text" name="subject" placeholder="Subject" required>
                                        <textarea name="message" rows="7" placeholder="Your Message"
                                                  required></textarea>
                                        <button class="btn-send btn-5 btn-5b ion-ios-paperplane">
                                            <span>Drop Me a Line</span></button>
                                    </div>
                                </div>    <!-- row -->
                            </form>
                        </div>
                    </article>
                </main>
            </div>
        </div>
    </div>
{% endblock %}

templates/zinnia/entry_list.html
{% extends "zinnia/base.html" %}
{% load i18n %}
{% load zinnia %}

{% block meta-description %}{% spaceless %}
    {% if category %}
        {% if category.description %}
            {{ category.description|striptags|safe }}
        {% else %}
            {% blocktrans with object=category %}The last entries categorized under {{ object }}{% endblocktrans %}
        {% endif %}
    {% endif %}

    {% if tag %}
        {% blocktrans with object=tag %}The last entries tagged with {{ object }}{% endblocktrans %}
    {% endif %}

    {% if author %}
        {% blocktrans with object=author %}The last entries by {{ object }}{% endblocktrans %}
    {% endif %}

{% endspaceless %}{% endblock meta-description %}

{% block meta-description-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %}
    {% blocktrans with object=page_obj.number %}page {{ object }}{% endblocktrans %}{% endifnotequal %}
{% endif %}{% endblock meta-description-page %}

{% block title %}{% spaceless %}
    {% if category %}
        {% blocktrans with object=category %}Category {{ object }}{% endblocktrans %}
    {% endif %}

    {% if tag %}
        {% blocktrans with object=tag %}Tag {{ object }}{% endblocktrans %}
    {% endif %}

    {% if author %}
        {% blocktrans with object=author %}Author {{ object }}{% endblocktrans %}
    {% endif %}

{% endspaceless %}{% endblock title %}

{% block title-page %}{% if page_obj %}{% ifnotequal page_obj.number 1 %} - {% blocktrans with object=page_obj.number %}
    Page {{ object }}{% endblocktrans %}{% endifnotequal %}{% endif %}{% endblock title-page %}

{% block link %}
    {{ block.super }}
    {% if category %}
        <link rel="alternate" type="application/rss+xml"
              title="{% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}"
              href="{% url 'zinnia:category_feed' category.tree_path %}"/>
    {% endif %}
    {% if tag %}
        <link rel="alternate" type="application/rss+xml"
              title="{% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}"
              href="{% url 'zinnia:tag_feed' tag.name %}"/>
    {% endif %}
    {% if author %}
        <link rel="alternate" type="application/rss+xml"
              title="{% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}"
              href="{% url 'zinnia:author_feed' author.get_username %}"/>
    {% endif %}
{% endblock link %}

{% block body-class %}entry-list{% if page_obj %} paginated page-{{ page_obj.number }}{% endif %}{% if category %}
    category category-{{ category.slug }}{% endif %}{% if tag %} tag tag-{{ tag|slugify }}{% endif %}{% if author %}
    author author-{{ author|slugify }}{% endif %}{% endblock body-class %}

{% block content %}

    {% block content-title %}
        {% if category %}
            <h1>{% blocktrans %}Category archives: {{ category }}{% endblocktrans %}</h1>
            {% if category.description %}
                <p>{{ category.description|striptags|safe }}</p>
            {% endif %}
            <p class="feed">
                <a href="{% url 'zinnia:category_feed' category.tree_path %}"
                   title="{% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}">
                    {% blocktrans with object=category %}RSS feed of {{ object }}{% endblocktrans %}
                </a>
            </p>
        {% endif %}

        {% if tag %}
            <h1>{% blocktrans %}Tag archives: {{ tag }}{% endblocktrans %}</h1>
            <p class="feed">
                <a href="{% url 'zinnia:tag_feed' tag.name %}"
                   title="{% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}">
                    {% blocktrans with object=tag %}RSS feed of {{ object }}{% endblocktrans %}
                </a>
            </p>
        {% endif %}

        {% if author %}
            <h1>{% blocktrans %}Author archives: {{ author }}{% endblocktrans %}</h1>
            <p class="feed">
                <a href="{% url 'zinnia:author_feed' author.get_username %}"
                   title="{% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}">
                    {% blocktrans with object=author %}RSS feed of {{ object }}{% endblocktrans %}
                </a>
            </p>
        {% endif %}
    {% endblock content-title %}

    {% block content-loop %}
        {% for object in object_list %}
            {% zinnia_loop_template object.content_template as template %}
            {% include template with object_content=object.html_preview continue_reading=1 %}
        {% empty %}
            <p class="info">
                <a href="{% url 'admin:zinnia_entry_add' %}">{% trans "No entries yet." %}</a>
            </p>
        {% endfor %}
    {% endblock content-loop %}

    {% block content-pagination %}
        {% if is_paginated %}
            {% zinnia_pagination page_obj %}
        {% endif %}
    {% endblock content-pagination %}

    {% block content-related %}
    {% endblock content-related %}

{% endblock content %}

{% block admin-tools %}
    {% if category and perms.zinnia.change_category %}
        <li>
            <a href="{% url 'admin:zinnia_category_change' category.pk %}" title="{% trans "Edit the category" %}">
                {% trans "Edit the category" %}
            </a>
        </li>
    {% endif %}
    {% if tag and perms.tagging.change_tag %}
        <li>
            <a href="{% url 'admin:tagging_tag_change' tag.pk %}" title="{% trans "Edit the tag" %}">
                {% trans "Edit the tag" %}
            </a>
        </li>
    {% endif %}
    {% if author and perms.auth.change_user %}
        <li>
            <a href="{% url 'change'|user_admin_urlname author.pk %}" title="{% trans "Edit the author" %}">
                {% trans "Edit the author" %}
            </a>
        </li>
    {% endif %}
{% endblock admin-tools %}

templates/zinnia/skeleton.html
{% load i18n %}
{% load staticfiles %}
<!doctype html>
<html lang="{{ LANGUAGE_CODE }}">
<head>
    <meta charset="utf-8">
    <title>{% block title %}{% endblock title %}{% block title-page %}{% endblock title-page %} - Zinnia's
        Weblog</title>
    <meta name="robots" content="follow, all"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <meta name="description" content="{% block meta-description %}{% trans "Just another Zinnia weblog." %}{% endblock meta-description %}{% block meta-description-page %}{% endblock meta-description-page %}"/>
    <meta name="keywords" content="{% block meta-keywords %}django, blog, weblog, zinnia{% endblock meta-keywords %}"/>
    <meta name="author" content="Fantomas42"/>
    {% block meta %}{% endblock meta %}
    <link rel="pingback" href="/xmlrpc/"/>
    <link rel="shortcut icon" href="{% static "zinnia/theme/img/favicon.ico" %}"/>
    <link rel="home" href="{% url 'zinnia:entry_archive_index' %}"/>
    <link rel="stylesheet" href="{% static "zinnia_twts/bootstrap/css/bootstrap.min.css" %}"/>
    <link rel="stylesheet" href="{% static "zinnia_twts/theme/css/github.css" %}"/>
    <link rel="stylesheet" href="{% static "zinnia_twts/ionicon/css/ionicons.min.css" %}"/>
    <link rel="stylesheet" type="text/css" media="screen, projection"
          href="{% static "zinnia_twts/theme/css/screen.css" %}"/>
    <link rel="stylesheet" type="text/css" media="print" href="{% static "zinnia_twts/theme/css/print.css" %}"/>
    <!--[if lt IE 8]>
        <link rel="stylesheet" type="text/css" media="screen, projection" href="{% static "zinnia/theme/css/ie.css" %}" />
    <![endif]-->
    {% block link %}{% endblock link %}
    <script src="{% static 'zinnia_twts/theme/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'zinnia_twts/bootstrap/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'zinnia_twts/theme/js/pace.min.js' %}"></script>
    <script src="{% static 'zinnia_twts/theme/js/modernizr.custom.js' %}"></script>
    {% block script %}{% endblock script %}
</head>
<body class="zinnia" {% block single_page %}{% endblock %}>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'zinnia:entry_archive_index' %}" title="Zinnia's Weblog" rel="home"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'zinnia:entry_archive_index' %}" title="Zinnia's Weblog" rel="home" data-hover="主页">主页</a></li>
                            <li class="cl-effect-11"><a href="{% url 'zinnia_twts:width_entry_index' %}" data-hover="博客">博客</a></li>
                            <li class="cl-effect-11"><a href="{% url 'zinnia_twts:about' %}" data-hover="关于">关于</a></li>
                            <li class="cl-effect-11"><a href="{% url 'zinnia_twts:contact' %}" data-hover="联系我">联系我</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="{% url 'zinnia:entry_search' %}">
{#                            <input type="text" name="pattern" placeholder="{% trans "Keywords..." %}" {% if pattern %}value="{{ pattern }}"{% endif %} />#}
{#                            <input type="submit" class="submitbutton" value="OK" />#}
                            <input type="search" name="pattern" placeholder="Search" {% if pattern %}value="{{ pattern }}"{% endif %} required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
    <div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
    {% block slider %}{% endblock slider %}
    {% block content_body %}
    <div class="content-body">
        <div class="container">
            <div class="row">
                {% block page_width %}
                    <main class="col-md-8">
                {% endblock %}
                    <div id="content" class="hfeed" role="main">
                        {% block content %}
                            <div class="links">
                                <h2>{% trans "Useful links" %}</h2>
                                <ul>
                                    <li>
                                        <a href="{% url 'zinnia:entry_archive_index' %}"
                                           title="{% trans "Weblog index" %}">
                                            {% trans "Weblog index" %}
                                        </a>
                                    </li>
                                    <li>
                                        <a href="{% url 'zinnia:sitemap' %}" title="{% trans "Sitemap" %}">
                                            {% trans "Sitemap" %}
                                        </a>
                                    </li>
                                </ul>
                            </div>
                            <div class="search">
                                <h2>{% trans "Search" %}</h2>
                                {% include "zinnia/tags/search_form.html" %}
                            </div>
                        {% endblock content %}
                    </div>
                </main>
                <aside class="col-md-4" role="complementary">
                    {% block sidebar %}
                    {% endblock sidebar %}
                </aside>
            </div>
        </div>
    </div>
    {% endblock %}
</div>
{#      <header id="header" role="banner">#}
{#        <nav>#}
{#          <ul class="top-navigation">#}
{#            <li>#}
{#              <a href="{% url 'zinnia:sitemap' %}" title="{% trans "Sitemap" %}" class="sitemap" rel="sitemap">#}
{#                {% trans "Sitemap" %}#}
{#              </a>#}
{#            </li>#}
{#            <li>#}
{#              <a href="{% url 'zinnia:entry_feed' %}" title="{% trans "RSS feed of last entries" %}" class="feeds">#}
{#                {% trans "RSS feed" %}#}
{#              </a>#}
{#            </li>#}
{#          </ul>#}
{#        </nav>#}
{#        <form method="get" action="{% url 'zinnia:entry_search' %}">#}
{#          <p>#}
{#            <input type="text" name="pattern" placeholder="{% trans "Keywords..." %}" {% if pattern %}value="{{ pattern }}"{% endif %} />#}
{#            <input type="submit" class="submitbutton" value="OK" />#}
{#          </p>#}
{#        </form>#}
{#        <h1>#}
{#          <a href="{% url 'zinnia:entry_archive_index' %}" title="Zinnia's Weblog" rel="home">#}
{#            Zinnia's Weblog#}
{#          </a>#}
{#        </h1>#}
{#        <blockquote>#}
{#          <p>{% trans "Just another Zinnia weblog." %}</p>#}
{#        </blockquote>#}
{#        {% block breadcrumbs %}{% endblock breadcrumbs %}#}
{#      </header>#}


{#    <footer id="footer" role="contentinfo">#}
{#        <p>{% blocktrans %}Powered by <a href="http://www.djangoproject.com">Django</a> and#}
{#            <a href="https://github.com/Fantomas42/django-blog-zinnia">Zinnia {{ ZINNIA_VERSION }}</a>#}
{#            .{% endblocktrans %}</p>#}
{#    </footer>#}
<footer id="site-footer" role="contentinfo">>
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy; 2016-2016 Powered by <a href="http://www.djangoproject.com">Django 1.9</a> and
                    <a href="https://github.com/Fantomas42/django-blog-zinnia">Zinnia {{ ZINNIA_VERSION }}</a>
                </p>
            </div>
        </div>
    </div>
</footer>
<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="{% url 'zinnia:entry_archive_index' %}">主页</a></li>
            <li><a href="{% url 'zinnia_twts:width_entry_index' %}">博客</a></li>
            <li><a href="{% url 'zinnia_twts:about' %}">关于</a></li>
            <li><a href="{% url 'zinnia_twts:contact' %}">联系我</a></li>
        </ul>
    </nav>
</div>
<script src="{% static 'zinnia_twts/theme/js/script.js' %}"></script>
</body>
</html>

templates/zinnia/tags/categories.html
{% load i18n %}
<ul class="{% if not categories %}no-{% endif %}categories">
  {% for category in categories %}
  <li{% if category.slug == context_category.slug %} class="current"{% endif %}>
    <a href="{{ category.get_absolute_url }}"
       title="{% blocktrans %}Show all entries in {{ category }}{% endblocktrans %}">{{ category }}</a>
    <span class="pull-right">{% blocktrans count entry_count=category.count_entries_published %}{{ entry_count }} entry{% plural %}{{ entry_count }} entries{% endblocktrans %}</span>
  </li>
  {% empty %}
  <li>
    {% trans "No categories yet." %}
  </li>
  {% endfor %}
</ul>

templates/zinnia/tags/entries_recent.html
{% load i18n %}
<ul class="{% if not entries %}no-{% endif %}entries-recent">
    {% for entry in entries %}
        <li>
            <a href="{{ entry.get_absolute_url }}" title="{{ entry.title }}" rel="bookmark">{{ entry.title }}</a>
        </li>
    {% empty %}
        <li>
            {% trans "No entries yet." %}
        </li>
    {% endfor %}
</ul>